### ISSUE TITLE
Country information source

### ISSUE THREAD

**Issue by pavel-odintsov** [emileaben/ixp-country-jedi#1]
Hello, folks!

Thanks for your nice toolkit! Could you help me? 

Where I can get information about city of router in traceroute in your tool?
![router geo loc](https://cloud.githubusercontent.com/assets/2744166/6593560/bed227e0-c7ea-11e4-88d0-f79e2c9c7744.png)

**Comment by emileaben** [comment]
Hi,
this is all crowdsourced info, so mappings are all based on user-input.
If you want info on a specific IP address, you can use this interface:
https://marmot.ripe.net/openipmap/ipmeta.json?ip=212.47.201.84
