### ISSUE TITLE
Please provide ability to work with few hundreds of probes

### ISSUE THREAD

**Issue by pavel-odintsov** [emileaben/ixp-country-jedi#2]
Hello!

I need visualization for 350+ probes because my country is very large (Russia).

But I got error: "probe count too high for viz (306), only fetching data for 51 (picked randomly)
This may take a while ...."

Could you optimize code and provide ability to work with huge amount of probes?

**Comment by emileaben** [comment]
there is an option 'max_probes' to get around that, so if you add:
&max_probes=400
to the URL things should work.

cheers,
Emile

**Comment by pavel-odintsov** [comment]
Thanks! Could you do this fix here https://atlas.ripe.net/measurements/1892250/#!openipmap or make it tunable?

**Comment by emileaben** [comment]
What you can do is go to the openipmap interface directly:
https://marmot.ripe.net/openipmap/tracemap?msm_ids=1892250&show_suggestions=0&max_probes=400

I can add the max-probes option to the direct openipmap interface, I put
that as an item to the openipmap github repository
https://github.com/emileaben/django-openipmap/issues/1
